server:
  port: 8080
spring:
  application:
    name: rating-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rating_system?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  type-aliases-package: com.tiv.rating.system.entity